# This file contains secrets for your Streamlit app
# You can add your secrets here, for example:
# api_key = "your-api-key"
# database_url = "your-database-url"

# For this app, we don't need any secrets yet 